name: Build

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Build debug APK
        run: ./gradlew clean assembleDebug

      - name: Create release and upload APK
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: "$(echo '${{ github.repository }}' | cut -d'/' -f2).apk"
          asset_content_type: application/zip
